version: '3.8'
services:
  mysql-server:
    image: mysql:8.0
    networks:
      - zbx_net
    ports:
      - $MYSQL_PORT:3306
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASS
      - MYSQL_DATABASE=$ZBX_DBNAME
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASS
    volumes:
      - zabbix-mysql:/var/lib/mysql

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:ubuntu-6.0-latest
    networks:
      - zbx_net
    ports:
      - $ZBX_PORT:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - ./zbx-data/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx-data/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx-data/export:/var/lib/zabbix/export:rw
      - ./zbx-data/modules:/var/lib/zabbix/modules:ro
      - ./zbx-data/enc:/var/lib/zabbix/enc:ro
      - ./zbx-data/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx-data/mibs:/var/lib/zabbix/mibs:ro
      - ./zbx-data/snmptraps:/var/lib/zabbix/snmptraps:rw
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=$ZBX_DBNAME
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASS
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASS
    depends_on:
      - mysql-server

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    networks:
      - zbx_net
    ports:
      - $ZBX_HTTP_PORT:8080
      - $ZBX_HTTPS_PORT:8443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx-nginx/ssl/:/etc/ssl/nginx:ro
      - ./zbx-nginx/modules/:/usr/share/zabbix/modules/:ro
    environment:
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=$ZBX_DBNAME
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASS
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASS
    depends_on:
      - mysql-server
      - zabbix-server-mysql
      
volumes:
  zabbix-mysql:
networks:
  zbx_net: